### ISSUE TITLE
OOM killed issue with version 3.20 

### ISSUE THREAD

**Issue by TiloGit** [IBM/ibm-cert-manager-operator#259] opened 2022-05-30 18:48 UTC
After the updated to 3.20 the controller pod get's killed with OOM. 

Default max is 300Mi, 

Seems it requires 500Mi with peaks to 700Mi.

Before on ibm-cert-manager-operator.v3.18.1 it stayed on 200 M consumption. 

Changed the CSV to 833Mi and the pod stayed stable (Deployment: ibm-cert-manager-operator)

Logs before the pod got killed: 
[ibm-cert-manager-operator-6f8d8b66dd-g9tsp-manager.log](https://github.com/IBM/ibm-cert-manager-operator/files/8800252/ibm-cert-manager-operator-6f8d8b66dd-g9tsp-manager.log)

Screenshot of Mem usage in OCP: 

![sshot-2022-05-30- 11-09-58 -mem-cert-manager](https://user-images.githubusercontent.com/6953606/171046576-acedef52-d0cc-4c7d-b48b-0d4b29751bdc.png)

![sshot-2022-05-30- 11-11-01 -mem-cert-manager](https://user-images.githubusercontent.com/6953606/171046575-57acf0c0-0b6b-4a18-aaa5-76a81d248c11.png)

**Comment by TiloGit** [comment] 2022-05-31 15:43
@bitscuit please assign.

**Comment by qpdpQ** [comment] 2022-05-31 22:56
This should be fixed in our upcoming release. You can get more info here: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53551#issuecomment-44318528

**Comment by TiloGit** [comment] 2022-05-31 23:00
@qpdpQ  Thanks for the info, can't see the detail. (no login)
Will you upper the max memory or fix a memory leak?

**Comment by qpdpQ** [comment] 2022-06-01 16:23
Based on @bitscuit "The root cause was in CS 3.18 cert-manager added a change to read a specific configmap, which caused it to cache all configmaps on the cluster. " And now we use another function to call the API server directly, this fix will be in the upcoming release, and for now, the workaround to increase memory limit should work.

**Closed** 2022-06-01 20:09 UTC
